In [1]:
import pandas as pd

In [2]:
from datetime import datetime, timedelta

In [3]:
#生成的样本业务字段文件label
label = pd.read_pickle('df_sample_v11.pkl')

In [4]:
label

,id,user_id,acq_channel,app_order_id,contract_no,repayment_date,installment_num,installment_amount,principal,interest,...,profit,original,is_extension,repaid_ltv,payout_ltv,profit_ltv,def_ltv,file_name,label,sample_type
0,244467,1317640458664894464,VIJG,1323701931170291712,1323702035390357504,2025-01-07,1,2200.0,2200.0,0.0,...,880.0,1,0,37159.0,24063.0,13096.0,0,df_1_2025-01-01.parquet,0,train
1,244468,1261698652018532352,APFL,1323702219562246144,1323702422545588224,2025-01-07,1,3200.0,3200.0,0.0,...,1280.0,1,0,53200.0,44648.0,8552.0,0,df_1_2025-01-01.parquet,0,train
2,244469,1258062236822757376,HLOA,1323703298987352064,1323703479929626624,2025-01-07,1,3050.0,3050.0,0.0,...,1220.0,1,0,81050.0,63432.0,17618.0,0,df_1_2025-01-01.parquet,0,train
3,244472,1258062236822757376,HLOA,1323706215282728960,1323706382891311104,2025-01-07,1,5500.0,5500.0,0.0,...,2199.0,1,0,78000.0,61602.0,16398.0,0,df_1_2025-01-01.parquet,0,train
4,244474,1318174204879134720,VIJG,1323669295601246208,1323677253802352640,2025-01-07,1,2800.0,2800.0,0.0,...,1120.0,1,0,8200.0,12632.0,-4432.0,1,df_2_2025-01-01.parquet,0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51831,341770,1297505747472965632,VIJG,1357734941040500736,1357735203289358336,2025-04-10,1,3700.0,3700.0,0.0,...,-2221.0,1,0,0.0,2221.0,-2221.0,1,df_1_2025-04-04.parquet,1,oot
51832,341772,1328698032113803264,VIJG,1357741567382315008,1357741815718666240,2025-04-10,1,1600.0,1600.0,0.0,...,-960.0,1,0,0.0,1920.0,-1920.0,1,df_2_2025-04-04.parquet,1,oot
51833,341773,1328698032113803264,VIJG,1357741567382315009,1357741848971108352,2025-04-10,1,1600.0,1600.0,0.0,...,-960.0,1,0,0.0,960.0,-960.0,1,df_2_2025-04-04.parquet,1,oot
51834,341775,1291054282550239232,APFL,1357747537718206464,1357747835765448704,2025-04-10,1,3200.0,3200.0,0.0,...,1280.0,1,0,6800.0,13562.0,-6762.0,1,df_1_2025-04-04.parquet,0,oot
51835,341776,1291054282550239232,APFL,1357747537722400768,1357747874600509440,2025-04-10,1,1800.0,1800.0,0.0,...,720.0,1,0,3600.0,11642.0,-8042.0,1,df_2_2025-04-04.parquet,0,oot

In [5]:
label['app_order_id'] = label['app_order_id'].astype(str)

In [6]:
#样本的申请时间写在下面范围
start_date = datetime.strptime('2025-01-01', '%Y-%m-%d')
end_date = datetime.strptime('2025-04-04', '%Y-%m-%d')
date_list = []
current_date = start_date
#循环
while current_date <= end_date:
    date_list.append(current_date.strftime('%Y-%m-%d'))
    current_date += timedelta(days=1)
print(date_list)

['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24', '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28', '2025-01-29', '2025-01-30', '2025-01-31', '2025-02-01', '2025-02-02', '2025-02-03', '2025-02-04', '2025-02-05', '2025-02-06', '2025-02-07', '2025-02-08', '2025-02-09', '2025-02-10', '2025-02-11', '2025-02-12', '2025-02-13', '2025-02-14', '2025-02-15', '2025-02-16', '2025-02-17', '2025-02-18', '2025-02-19', '2025-02-20', '2025-02-21', '2025-02-22', '2025-02-23', '2025-02-24', '2025-02-25', '2025-02-26', '2025-02-27', '2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07', '2025-03-08', '2025-03-09', '2025-03-10', '2025-03-11', '2025-03-12', '2025-03-13', '2025-03-14', '2025-03-15', '2025-03-16', '2025-03-17', '2025-03-18', '2025-03-19', '2025-03-20', '2025-03-21', '2025-03-22', '2025-03-23', '2025-03-24', '2025-03-25', '2025-03-26', '2025-03-27', '2025-03-28', '2025-03-29', '2025-03-30', '2025-03-31', '2025-04-01', '2025-04-02', '2025-04-03', '2025-04-04']

In [7]:
file_path = '/home/zengjunyao/model_link/ath/'

In [8]:
#选取的模块名称
#model_list = ["loan_th_base_v2","loan_th_base_v3_2","sms_th_loan0_v1","app_th_bcate_v1","app_th_loan_v2","dev_th_base_v1","dev_th_base_v2","ui_th_base_v2"]
model_list = ["loan_th_base_v2",
                      "sms_th_loan0_v1",
                      "app_th_loan_v2",
                      "dev_th_base_v2","ui_th_base_v2"]

In [9]:
#将选取的模块所有特征及不同时期的数据合并df_all_feature
df_all_feature = label[['app_order_id']]   #初始化df_all_feature：所有特征
# df_all_feature = pd.DataFrame()
for model in model_list:    #遍历每一个模块
    df_model = pd.DataFrame()    #每个模型创建一个 df_model
    for date in date_list:  
        #读取该模型在不同日期下的数据，将其逐次合并到 df_model里(按列拼接)
        try:
            df_tmp1 = pd.read_parquet(file_path + model + f'/df_1_{date}.parquet')
            df_tmp2 = pd.read_parquet(file_path + model + f'/df_2_{date}.parquet')
            df_model = pd.concat([df_model,df_tmp1,df_tmp2])
        except:  #同时处理可能出现的读取文件错误
            print(model,date)
    #合并：将所有模型的df_model按行合并到df_all_feature     
    df_all_feature = pd.merge(df_all_feature,df_model,on = 'app_order_id',how='left')   
    print(model,df_model.shape[0])

loan_th_base_v2 58947
sms_th_loan0_v1 58947
app_th_loan_v2 58947
dev_th_base_v2 58947
ui_th_base_v2 58947

In [10]:
df_all_feature

,app_order_id,loan_th_base_v2_extension_extorder_num_cnt15_acq0,loan_th_base_v2_extension_extorder_num_cnt15_acq1,loan_th_base_v2_extension_extorder_num_cnt15_all,loan_th_base_v2_extension_extorder_num_cnt15_holiday0,loan_th_base_v2_extension_extorder_num_cnt15_holiday1,loan_th_base_v2_extension_extorder_num_cnt15_product0,loan_th_base_v2_extension_extorder_num_cnt15_product1,loan_th_base_v2_extension_extorder_num_cnt15_time0-5,loan_th_base_v2_extension_extorder_num_cnt15_time13-18,...,ui_th_base_v2_user_marriage_status,ui_th_base_v2_user_mid_name_len,ui_th_base_v2_user_month_income,ui_th_base_v2_user_register_fill_timediff,ui_th_base_v2_user_register_order_timediff,ui_th_base_v2_user_salary_pay_frequency,ui_th_base_v2_user_second_contact_name_len,ui_th_base_v2_user_second_contact_relationship,ui_th_base_v2_user_work_type,ui_th_base_v2_user_work_years
0,1323701931170291712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,12,1,0.0408,401.4764,0,3,5,1,0
1,1323702219562246144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3,13,3,0.0497,4106.3836,0,14,0,1,3
2,1323703298987352064,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,6,4,0.4508,2840.9486,0,8,0,1,3
3,1323706215282728960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,6,4,0.4508,2841.1419,0,8,0,1,3
4,1323669295601246208,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,11,2,0.0219,363.9472,0,25,5,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51831,1357734941040500736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3,9,2,0.0006,3105.5678,0,4,0,3,3
51832,1357741567382315008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,9,2,0.0456,1647.1117,0,3,5,1,0
51833,1357741567382315009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,9,2,0.0456,1647.1117,0,3,5,1,0
51834,1357747537718206464,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,11,2,0.0375,4416.9603,0,5,0,1,3
51835,1357747537722400768,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,11,2,0.0375,4416.9603,0,5,0,1,3

In [10]:
#空值填充-999
df_all_feature.fillna(-999,inplace=True)

In [11]:
df_all_feature = df_all_feature[df_all_feature['app_order_id'].isin(label['app_order_id'])]#确保df_all_feature的订单号在选取的样本内

In [12]:
df_all_feature.index=range(df_all_feature.shape[0])  #重置索引

In [13]:
import warnings
# 忽略所有警告
warnings.filterwarnings("ignore")
# 你的代码

In [14]:
#删除所有数据类型不是数值型的列
for i in df_all_feature.columns[1:]:
    try:
        df_all_feature[i] = df_all_feature[i].astype(float)
    except:
        print(i)
        del df_all_feature[i]

In [15]:
#保留所有单列值不是同一值的列
DF_columns = []
for i in df_all_feature.columns:
    if df_all_feature[i].value_counts().shape[0] > 1:
        DF_columns.append(i)

In [16]:
#保存特征文件
df_all_feature[DF_columns].to_parquet('a11_all_feature.parquet')

In [17]:
#读取特征文件
sample = pd.read_parquet('a11_all_feature.parquet')
print(sample.shape)
sample.head(2)

(51836, 9551)

,app_order_id,loan_th_base_v2_extension_extorder_num_cnt15_acq0,loan_th_base_v2_extension_extorder_num_cnt15_acq1,loan_th_base_v2_extension_extorder_num_cnt15_all,loan_th_base_v2_extension_extorder_num_cnt15_holiday0,loan_th_base_v2_extension_extorder_num_cnt15_holiday1,loan_th_base_v2_extension_extorder_num_cnt15_product0,loan_th_base_v2_extension_extorder_num_cnt15_product1,loan_th_base_v2_extension_extorder_num_cnt15_time0-5,loan_th_base_v2_extension_extorder_num_cnt15_time13-18,...,ui_th_base_v2_user_line_account_symbol_len,ui_th_base_v2_user_marriage_status,ui_th_base_v2_user_mid_name_len,ui_th_base_v2_user_month_income,ui_th_base_v2_user_register_fill_timediff,ui_th_base_v2_user_register_order_timediff,ui_th_base_v2_user_second_contact_name_len,ui_th_base_v2_user_second_contact_relationship,ui_th_base_v2_user_work_type,ui_th_base_v2_user_work_years
0,1323701931170291712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,12.0,1.0,0.0408,401.4764,3.0,5.0,1.0,0.0
1,1323702219562246144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,3.0,13.0,3.0,0.0497,4106.3836,14.0,0.0,1.0,3.0